version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: chatgpt_clone_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chatgpt_clone
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chatgpt_clone"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
