spring:
  ai:
    openai:
      base-url: http://localhost:12434/engines
      api-key: dummy
      chat:
        options:
          model: ai/llama3.2:latest
      embedding:
        options:
          model: ai/granite-embedding-multilingual:latest
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
#        dimensions: 768
        max-document-batch-size: 1000
  datasource:
    url: jdbc:postgresql://localhost:5432/chatgpt_clone
    username: chat
    password: chat
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

google:
  cse:
    api-key: ${GOOGLE_CSE_API_KEY:}
    cx: ${GOOGLE_CSE_CX:}
    timeout-ms: 8000
