spring:
  ai:
    ollama:
      chat:
        options:
          model: llava:latest
      embedding:
        options:
          model: all-minilm
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        #        dimensions: 768
        max-document-batch-size: 1000
  datasource:
    url: jdbc:postgresql://localhost:5432/chatgpt_clone
    username: chat
    password: chat
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

google:
  cse:
    api-key: ${GOOGLE_CSE_API_KEY:}
    cx: ${GOOGLE_CSE_CX:}
    timeout-ms: 8000
